---
  apiVersion: v1
  kind: Service
  metadata:
    name: bamoe-canvas
    namespace: bamoe
    labels:
      app: bamoe-canvas
  spec:
    ports:
      - port: 8080
        protocol: TCP
        targetPort: 8080
    type: LoadBalancer
    selector:
      app: bamoe-canvas
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bamoe-canvas
  namespace: bamoe
  labels:
    app:  bamoe-canvas
spec:
  selector:
    matchLabels:
      app: bamoe-canvas
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: bamoe-canvas
    spec:
      containers:
        - image: quay.io/bamoe/canvas:9.1.0-ibm-0001
          imagePullPolicy: Always
          name: bamoe-canvas
          env:
            - name: KIE_SANDBOX_EXTENDED_SERVICES_URL
              value: http://169.50.115.195:21345 
            - name: KIE_SANDBOX_GIT_CORS_PROXY_URL
              value: http://169.50.115.196:8080
          ports:
            - containerPort: 8080