apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: process-example-app
  name: process-example-app
spec:
  securityContext:
    fsGroup: 0
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: process-example-app
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose.yml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: process-example-app
    spec:
      containers:
        - env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka.bamoe-app.svc.cluster.local:9092
            - name: KOGITO_DATAINDEX_HTTP_URL
              value: http://data-index.bamoe-app.svc.cluster.local:8080/graphql
            - name: KOGITO_JOBS_SERVICE_URL
              value: http://management-console.bamoe-app.svc.cluster.local:8080/JobsManagement
            - name: KOGITO_SERVICE_URL
              value: http://management-console.bamoe-app.svc.cluster.local:8080/ProcessInstances
            - name: QUARKUS_DATASOURCE_JDBC_URL
              value: jdbc:postgresql://postgresql.bamoe-app.svc.cluster.local:5432/bamoe
            - name: QUARKUS_DATASOURCE_REACTIVE_URL
              value: jdbc:postgresql://postgresql.bamoe-app.svc.cluster.local:5432/bamoe
            - name: QUARKUS_DATASOURCE_USERNAME
              value: bamoe_poc
            - name: QUARKUS_DATASOURCE_PASSWORD
              value: password
            - name: QUARKUS_FLYWAY_PLACEHOLDERS_USER
              value: bamoe_poc
            - name: QUARKUS_HTTP_CORS_ORIGINS
              value: /.*/
          image: bamoe-poc/bamoe-process-example:latest
          name: process-example-app
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /home/kogito/data/svg
              name: process-example-app-claim0
      restartPolicy: Always
      volumes:
        - name: process-example-app-claim0
          persistentVolumeClaim:
            claimName: process-example-app-claim0
