apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: process-example-app-claim0
  name: process-example-app-claim0
spec:
  storageClassName: ibmc-block-bronze
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
