apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: kafka-magic-config
  name: kafka-magic-config
spec:
  storageClassName: ibmc-block-bronze
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
