---
name: "canvas"
kie-sandbox-helm-chart:
  kie_sandbox:
    image:
      registry: "quay.io"
      account: "bamoe"
      name: "canvas"
      tag: "9.1.0-ibm-0001"
      pullPolicy: "IfNotPresent"
  extended_services:
    image:
      registry: "quay.io"
      account: "bamoe"
      name: "extended-services"
      tag: "9.1.0-ibm-0001"
      pullPolicy: "IfNotPresent"
  cors_proxy:
    image:
      registry: "quay.io"
      account: "bamoe"
      name: "cors-proxy"
      tag: "9.1.0-ibm-0001"
      pullPolicy: "IfNotPresent"
global:
  ingressSource: ""
  kubernetesIngressClass: ""
  kubernetesClusterDomain: ""
  openshiftRouteDomain: ""
