apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: keycloak
  name: keycloak
spec:
  ports:
    - name: "8999"
      port: 8999
      targetPort: 8080
  selector:
    io.kompose.service: keycloak
