apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: keycloak
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: keycloak
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose.yml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: keycloak
    spec:
      containers:
        - env:
            - name: KEYCLOAK_IMPORT
              value: /tmp/kogito-realm.json
            - name: KEYCLOAK_PASSWORD
              value: admin
            - name: KEYCLOAK_USER
              value: admin
          image: quay.io/keycloak/keycloak:legacy
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:8080/auth/realms/kogito
            failureThreshold: 50
            periodSeconds: 1
            timeoutSeconds: 1
          name: bamoe-poc-keycloak
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /tmp/kogito-realm.json
              name: keycloak-cm0
              subPath: kogito-realm.json
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: kogito-realm.json
                path: kogito-realm.json
            name: keycloak-cm0
          name: keycloak-cm0
